apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sample-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chanducherry911/efk-argo-lab.git
    targetRevision: main
    path: nginx-helm/nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
